use_frameworks!

platform :ios, '9.0'

target 'XZshenChunDemo_Example' do
  pod 'XZshenChunDemo', :path => '../'

  target 'XZshenChunDemo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
